version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  jest_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run lint
      - run: npm test
      - store_test_results:
          path: ~/repo/junit.xml

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - jest_test:
          requires:
            - build
